# Generated by Django 4.1.6 on 2023-06-13 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_userdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='fullname',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='userdata',
            name='lastname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='othername',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
