# Generated by Django 4.1.6 on 2023-06-13 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_userdata_user_alter_userdata_college_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='matric_no',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
