# Generated by Django 4.1.6 on 2023-06-14 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_userdata_matric_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
